import { Header } from "@/components/header";
import { Popbar } from "@/components/popbar";
import { Sidebar } from "@/components/sidebar";
import { PopbarProvider } from "@/hooks/usePopbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PopbarProvider>
      <div className="flex flex-row flex-nowrap w-full h-full">
        <Sidebar />
        <Popbar />
        <main className="relative flex-1 overflow-y-auto overflow-x-hidden">
          <Header />

          {children}
        </main>
      </div>
    </PopbarProvider>
  );
}
